backend:
  name: github
  repo: veronikastoyanova/test

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: audience, label: Audience, widget: select, options: ['shipper', 'carrier'], default: ['shipper'] }
      - { name: shortDescription, label: Short Description }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - { name: type, label: Type, widget: select, options: ['blog', 'webinar'], default: ['blog'] }